# Generated by Django 5.0.6 on 2024-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
